#! /bin/sh
### BEGIN INIT INFO
# Provides:          git-daemon 
# Required-Start:    mysql 
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GIT-Daemon server daemon
# Description:       Starts the GIT-Daemon needed by Gitorious
### END INIT INFO

# Author: Fabio Akita <fabioakita@gmail.com>

RUBY_HOME="/opt/ruby-enterprise"
GITORIOUS_HOME="/var/www/gitorious"
RETVAL=0
PROG="git-daemon"
GIT_DAEMON="$RUBY_HOME/bin/ruby $GITORIOUS_HOME/script/git-daemon -d"
LOCK_FILE=/var/lock/git-daemon
PID_FILE=$GITORIOUS_HOME/log/git-daemon.pid
 
do_check_pid() {
  if [ -f $PID_FILE ]; then
    PID=`cat $PID_FILE`
    RUNNING=`ps --pid $PID | wc -l`
  else
    PID=0
    RUNNING=0
  fi
}
 
runlevel=`runlevel | awk '{print $2}'`
 
start()
{
  do_check_pid
  if [ $RUNNING != 2 ] ; then
    echo -n "Starting $PROG"
    /bin/su - git -c "$GIT_DAEMON" 2>/dev/null
    sleep 1
    if [ -f $PID_FILE ] ; then
      echo "."
      RETVAL=0
    else
      echo ": FAILURE!!!"
      RETVAL=1
    fi
  else
    echo "$PROG already running"
    RETVAL=1
  fi
  [ "$RETVAL" = 0 ] && touch $LOCK_FILE
}
 
stop()
{
  do_check_pid
  if [ $RUNNING != 2 ] ; then
    echo "$PROG not running"
  else
    echo -n "Stopping $PROG"
    PROGPID=`cat $PID_FILE`
    kill -TERM $PROGPID && echo "."
  fi
  RETVAL=0
  # if we are in halt or reboot runlevel kill all running sessions
  # so the TCP connections are closed cleanly
  if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
    PROGPID=`cat $PID_FILE`
    kill -9 $PROGPID > /dev/null
  fi
  [ "$RETVAL" = 0 ] && {
    rm -f $LOCK_FILE && rm -f $PID_FILE
  }
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
    restart)
        stop
        start
        ;;
  condrestart)
    if [ -f $LOCK_FILE ] ; then
      if [ "$RETVAL" = 0 ] ; then
        stop
        # avoid race
        sleep 10
        start
      fi
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|condrestart}"
    RETVAL=1
esac
exit $RETVAL
