#!/bin/bash
### BEGIN INIT INFO
# Provides:          Gitorious stompserver
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: stompserver daemon
# Description:       Starts the stompserver needed by Gitorious
### END INIT INFO
#

RUBY_HOME="/opt/ruby-enterprise"
GEMS_HOME="/usr"
GITORIOUS_HOME="/var/www/gitorious"
RETVAL=0
PROG="stompserver"
STOMP="$RUBY_HOME/bin/ruby $GEMS_HOME/bin/stompserver -w $GITORIOUS_HOME/tmp/stomp -q file -s queue &> /dev/null &"
LOCK_FILE=/var/lock/stomp
PID_FILE=$GITORIOUS_HOME/tmp/stomp/log/stompserver.pid

# Source lsb functions for killproc
. /lib/lsb/init-functions
 
do_check_pid() {
  if [ -f $PID_FILE ]; then
    PID=`cat $PID_FILE`
    RUNNING=`ps --pid $PID | wc -l`
  else
    PID=0
    RUNNING=0
  fi
}
 
runlevel=$(set -- $(runlevel); eval "echo $$#" )
 
start()
{
  do_check_pid
  if [ $RUNNING != 2 ] ; then
    echo -n "Starting $PROG: "
    /bin/su - git -c "$STOMP"
    sleep 4
    if [ -f $PID_FILE ] ; then
      echo "Success"
      RETVAL=0
    else
      echo "FAILURE"
      RETVAL=1
    fi
  else
    echo "$PROG already running"
    RETVAL=1
  fi
  [ "$RETVAL" = 0 ] && touch $LOCK_FILE
  echo
}
 
stop()
{
  do_check_pid
  echo -n "Stopping $PROG: "
  if [ $RUNNING != 2 ] ; then
    echo "$PROG was not properly running"
    RETVAL=1
  else
    killproc -p $PID_FILE
    RETVAL=$?
  fi
  # if we are in halt or reboot runlevel kill all running sessions
  # so the TCP connections are closed cleanly
  if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
    killproc -p $PID 2>/dev/null
  fi
  if [ "$RETVAL" = 0 ] ; then
    rm -f $LOCK_FILE
    echo "Success"
  else
    echo "FAILURE"
  fi
  echo
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
restart)
stop
start
;;
  condrestart)
    if [ -f $LOCK_FILE ] ; then
      if [ "$RETVAL" = 0 ] ; then
        stop
        # avoid race
        sleep 5
        start
      fi
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|condrestart}"
    RETVAL=1
esac
exit $RETVAL
