#!/usr/bin/env ruby
require File.dirname(__FILE__)+'/../config/environment'
ActionMailer::Base.raise_delivery_errors = false
ActionMailer::Base.delivery_method = :test

if User.find_by_is_admin(true)
  puts "You already have an Administrator"
  exit!
end

puts "Type in Administrator's e-mail: "
email = gets.strip
puts "Type in Administrator's password: "
password = gets.strip

user = User.new(:email => email, :terms_of_use => '1')
user.password = password
user.password_confirmation = password
user.login = 'admin'
user.is_admin = true
if user.save
  user.activate
  puts "Admin user created successfully."
else
  puts "Failed creating Admin user."
end
