#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'
require 'geoip'
require 'socket'

ENV["RAILS_ENV"] ||= "production"
require File.dirname(__FILE__)+'/../config/environment'

Rails.configuration.log_level = :info # Disable debug

BASE_PATH = File.expand_path(GitoriousConfig['repository_base_path'])

MAX_CHILDREN = 35
$children_reaped = 0
$children_active = 0

module Git

class Daemon
  include Daemonize
  
  def self.start
    new
  end
  
  def initialize
    daemonize(File.join(RAILS_ROOT, "log", "git-daemon.log"))
    
    @geoip = GeoIP.new(File.join(RAILS_ROOT, "data", "GeoIP.dat"))
    trap "CLD" do
      pid = Process.wait
      $children_reaped += 1
      log(pid, "Disconnected. (status=#{$?.exitstatus})")
      
      $children_reaped = $children_active = 0 if $children_reaped == $children_active
    end
    
    port = 9418
    server = TCPServer.new('localhost', port)
    service_regexp = /(\w{4})(git-[\w-]+)\s(.+)\x0host=([\w\.\-]+)/.freeze
    while session = server.accept
      $children_active += 1
      
      if $children_active - $children_reaped > MAX_CHILDREN
        session.close
        next
      end
      
      line = session.recv(1000)
      timeout = 30
      if line =~ service_regexp
        code = $1
        service = $2
        path = $3
        host = $4
        
        path = "#{BASE_PATH}/#{path}"
        if !File.directory?(path)
          log(Process.pid, "Invalid path: #{path}")
          session.close
          next
        end
        
        if !File.exist?(File.join(path, "git-daemon-export-ok"))
          session.close
          next
        end
        
        Dir.chdir(path) do
          cmd = "git-upload-pack --strict --timeout=#{timeout} ."
          
          fork do
            repository = nil
            begin
              ActiveRecord::Base.allow_concurrency = true
              repository = ::Repository.find_by_path(path)
            rescue Exception
            end
            pid = Process.pid
            ip_family, port, name, ip = session.peeraddr
            log(pid, "Connection from #{ip}")
            
            $stdout.reopen(session)
            $stdin.reopen(session)
            session.close
            
            if repository
							if ip_family == "AF_INET6"
								repository.cloned_from(ip)
							else
              	localization = @geoip.country(ip)
              	repository.cloned_from(ip, localization[3], localization[5])
							end
            else
              log(pid, "Cannot find repository: #{path}")
            end
            
            exec(cmd)
            
            exit!
          end
        end
      else
        $stderr.puts "Invalid request: #{line}"
        session.close
      end
    end
  end
  
  def log(pid, msg)
    $stderr.puts "[#{pid}] #{msg}"
  end
end

end

trap "SIGINT" do
  $stderr.puts "Exiting..."
  exit 0
end

Git::Daemon.start
