#!/usr/bin/env ruby

require "pathname"

RAILS_ENV = ENV['RAILS_ENV'] ||= 'production'

filename = ARGV[0]
if filename.nil?
  warn "You need to supply a target file!"
  exit!
end

rails_root = (Pathname(__FILE__) + "../../")
Dir.chdir(rails_root)
require "./config/environment"
#require (Pathname(__FILE__) + "../../config/environment").realpath

SshKeyFile.regenerate(filename)
