#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

$DEBUG = false

repos_to_gc = Repository.all_due_for_gc(ARGV[0])
if $DEBUG
  puts "Garbage collecting #{repos_to_gc.length} repositories:"
  puts "=" * 72
end

repos_to_gc.each do |repo|
  puts "Garbage collecting #{repo.url_path} (#{repo.id})" if $DEBUG
  unless repo.gc!
    $stderr.puts "GC FAIL: Repository##{repo.id} (#{repo.url_path}"
  end
end
