#!/usr/bin/env ruby                                                                  
#                                                                                    
# This file can be Exec'ed without spawning a new shell
# It lets you control Unicorn with a full Gitorious environment
#                                                                                    
require "pathname"
RAILS_ROOT = (Pathname(__FILE__) + "../../").realpath.to_s

ENV["BUNDLE_GEMFILE"] = Pathname(RAILS_ROOT) + "Gemfile"

ENV["RAILS_ENV"] = "production"
require 'rubygems'
require 'bundler/setup'

load Gem.bin_path('unicorn', 'unicorn_rails')
