#!/bin/bash
#--
#   Copyright (C) 2012-2014 Gitorious AS
#   Copyright (C) 2009 Marius Mårnes Mathiesen <marius.mathiesen@gmail.com>
#   Copyright (C) 2008 Johan Sørensen <johan@johansorensen.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

set -e # exit on error immediately

INTERNAL_API_URL=${INTERNAL_API_URL:-"http://localhost:3000/api/internal"}

notify() {
  local oldsha=$1
  local newsha=$2
  local refname=$3

  url="$INTERNAL_API_URL/hooks/post-receive"
  curl -q -L -s -o /dev/null -X POST --data-urlencode "username=$GITORIOUS_USER" --data-urlencode "repo_path=$GITORIOUS_REPOSITORY_PATH" --data-urlencode "repository_id=$GITORIOUS_REPOSITORY_ID" --data-urlencode "refname=$refname" --data-urlencode "oldsha=$oldsha" --data-urlencode "newsha=$newsha" "$url" &
}

lines=()
while read oldsha newsha refname; do
  notify $oldsha $newsha $refname
  lines+=("$oldsha $newsha $refname")
done

# Run custom post-receive hook (if any)
if [ -n "$GITORIOUS_CUSTOM_POST_RECEIVE_PATH" ]; then
  (IFS=$'\n'; echo "${lines[*]}") | exec $GITORIOUS_CUSTOM_POST_RECEIVE_PATH
fi
