#!/bin/bash
#--
#   Copyright (C) 2012-2014 Gitorious AS
#   Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

set -e # exit on error immediately

# If GITORIOUS_PROTO is empty it's a local push.
# Local pushes come from the app itself (merge request update from UI etc).
if [ -z "$GITORIOUS_PROTO" ]; then
  exit 0 # exit with success, skipping custom hook
fi

INTERNAL_API_URL=${INTERNAL_API_URL:-"http://localhost:3000/api/internal"}

authorize() {
  local oldsha=$1
  local newsha=$2
  local refname=$3
  local mergebase=$(git merge-base $oldsha $newsha 2>/dev/null || true)

  url="$INTERNAL_API_URL/hooks/pre-receive"
  response=$(curl -q -L -s -o - -w '\n%{http_code}' --get --data-urlencode "username=$GITORIOUS_USER" --data-urlencode "repository_id=$GITORIOUS_REPOSITORY_ID" --data-urlencode "refname=$refname" --data-urlencode "oldsha=$oldsha" --data-urlencode "newsha=$newsha" --data-urlencode "mergebase=$mergebase" "$url" || true)

  status=$(echo "$response" | tail -n1)
  message=$(echo "$response" | head -n1)

  if [[ $status != "200" ]]; then
    if [[ $status == "403" ]]; then
      echo "$message" >&2
    else
      echo "Error occured, please contact support" >&2
    fi

    exit 1
  fi
}

lines=()
while read oldsha newsha refname; do
  authorize $oldsha $newsha $refname
  lines+=("$oldsha $newsha $refname")
done

# Run custom pre-receive hook (if any)
if [ -n "$GITORIOUS_CUSTOM_PRE_RECEIVE_PATH" ]; then
  (IFS=$'\n'; echo "${lines[*]}") | exec $GITORIOUS_CUSTOM_PRE_RECEIVE_PATH
fi
