#!/usr/bin/env ruby
#--
#   Copyright (C) 2012-2013 Gitorious AS
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++
require "pathname"
$: << File.join(File.dirname(Pathname.new(__FILE__).realpath), "../../lib")
require "gitorious/custom_hook"

# NOTE: Any core Gitorious update operations goes here at the top (none so far).

hook = Gitorious::CustomHook.new("update", ENV["RAILS_ENV"] || "production")

if hook.executable?
  status = hook.execute(ARGV)

  if !status.success?
    puts "Custom update hook failed, exiting with its code"
    exit(status.exitstatus)
  end
end
